//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScriptNotepad.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScriptNotepad.Localization.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Server Pages script file|*.asp|A text in a file dialog indicating Active Server Pages script files.
        /// </summary>
        internal static string msgActiveServerPagesScriptFile {
            get {
                return ResourceManager.GetString("msgActiveServerPagesScriptFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ada file|*.ada;*.ads;*.adb|A text in a file dialog indicating Ada files.
        /// </summary>
        internal static string msgAdaFile {
            get {
                return ResourceManager.GetString("msgAdaFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All types|*.*|A text in a file dialog indicating all files.
        /// </summary>
        internal static string msgAllFileTypes {
            get {
                return ResourceManager.GetString("msgAllFileTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScriptNotepad [{0}]|As in the application name combined with an active file name.
        /// </summary>
        internal static string msgAppTitleWithFileName {
            get {
                return ResourceManager.GetString("msgAppTitleWithFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly language source file|*.asm|A text in a file dialog indicating Assembly language source files.
        /// </summary>
        internal static string msgAssemblySourceFile {
            get {
                return ResourceManager.GetString("msgAssemblySourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoIt|*.au3|A text in a file dialog indicating AutoIt files.
        /// </summary>
        internal static string msgAutoItFile {
            get {
                return ResourceManager.GetString("msgAutoItFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch file|*.bat;*.cmd;*.nt|A text in a file dialog indicating Batch files.
        /// </summary>
        internal static string msgBatchFile {
            get {
                return ResourceManager.GetString("msgBatchFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorical Abstract Machine Language|*.ml;*.mli;*.sml;*.thy|A text in a file dialog indicating Categorical Abstract Machine Language files.
        /// </summary>
        internal static string msgCategoricalAbstractMachineLanguageFile {
            get {
                return ResourceManager.GetString("msgCategoricalAbstractMachineLanguageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMake file|*.cmake|A text in a file dialog indicating CMake files.
        /// </summary>
        internal static string msgCMakeFile {
            get {
                return ResourceManager.GetString("msgCMakeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffee Script file|*.litcoffee|A text in a file dialog indicating Coffee Script files.
        /// </summary>
        internal static string msgCoffeeScriptLanguage {
            get {
                return ResourceManager.GetString("msgCoffeeScriptLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ln: {0}  Col: {1}|As in the current column and the current line in a ScintillaNET control.
        /// </summary>
        internal static string msgColLine {
            get {
                return ResourceManager.GetString("msgColLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sel1: {0}|{1}  Sel2: {2}|{3}  Len: {4}|The selection start, end and length in a ScintillaNET control in columns, lines and character count.
        /// </summary>
        internal static string msgColLineSelection {
            get {
                return ResourceManager.GetString("msgColLineSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Business Oriented Language|*.cbl;*.cbd;*.cdb;*.cdc;*.cob|A text in a file dialog indicating Common Business Oriented Language files.
        /// </summary>
        internal static string msgCommonBusinessOrientedLanguage {
            get {
                return ResourceManager.GetString("msgCommonBusinessOrientedLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C++ source file|*.h;*.hpp;*.hxx;*.cpp;*.cxx;*.cc|A text in a file dialog indicating C++ source files.
        /// </summary>
        internal static string msgCPPSourceFile {
            get {
                return ResourceManager.GetString("msgCPPSourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C source file|*.c|A text in a file dialog indicating C source files.
        /// </summary>
        internal static string msgCSSourceFile {
            get {
                return ResourceManager.GetString("msgCSSourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cascading Style Sheets File|*.css|A text in a file dialog indicating Cascading Style Sheets files.
        /// </summary>
        internal static string msgCSSSourceFile {
            get {
                return ResourceManager.GetString("msgCSSSourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A line script snippet|As in a script for manipulating Scintilla contents as lines.
        /// </summary>
        internal static string msgDefaultScriptSnippetLines {
            get {
                return ResourceManager.GetString("msgDefaultScriptSnippetLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A text script snippet|As in a script for manipulating Scintilla contents as text.
        /// </summary>
        internal static string msgDefaultScriptSnippetText {
            get {
                return ResourceManager.GetString("msgDefaultScriptSnippetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diff file|*.diff;*.patch|A text in a file dialog indicating Diff files.
        /// </summary>
        internal static string msgDiffFile {
            get {
                return ResourceManager.GetString("msgDiffFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to length: {0}  lines: {1}|As in the ScintillaNET document size in lines and in characters.
        /// </summary>
        internal static string msgDocSizeLines {
            get {
                return ResourceManager.GetString("msgDocSizeLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D programming language|*.d|A text in a file dialog indicating D programming language files.
        /// </summary>
        internal static string msgDSourceFile {
            get {
                return ResourceManager.GetString("msgDSourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error|A message describing that some kind of error occurred..
        /// </summary>
        internal static string msgError {
            get {
                return ResourceManager.GetString("msgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A script error occurred on the database update|Something failed during running the database update script.
        /// </summary>
        internal static string msgErrorInScript {
            get {
                return ResourceManager.GetString("msgErrorInScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eXtensible Markup Language file|*.xml;*.xsml;*.xls;*.xsd;*.kml;*.wsdl;*.xlf;*.xliff|A text in a file dialog indicating eXtensible Markup Language files.
        /// </summary>
        internal static string msgeXtensibleMarkupLanguageFile {
            get {
                return ResourceManager.GetString("msgeXtensibleMarkupLanguageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file has been changed|A caption message for a message dialog which will ask if a changed file should be reloaded.
        /// </summary>
        internal static string msgFileArbitraryFileChange {
            get {
                return ResourceManager.GetString("msgFileArbitraryFileChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; has been changed. Reload from the file system?|As in the opened file has been changed outside the software so do as if a reload should happed.
        /// </summary>
        internal static string msgFileHasChanged {
            get {
                return ResourceManager.GetString("msgFileHasChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash ActionScript file|*.as;*.mx|A text in a file dialog indicating Flash ActionScript files.
        /// </summary>
        internal static string msgFlashActionScriptFile {
            get {
                return ResourceManager.GetString("msgFlashActionScriptFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fortran free form source file|*.f;*.for;*.f90;*.f95;*.f2k|A text in a file dialog indicating Fortran free form source files.
        /// </summary>
        internal static string msgFortranFreeFormSourceFile {
            get {
                return ResourceManager.GetString("msgFortranFreeFormSourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haskell source file|*.hs;*.lhs;*.as;*.las|A text in a file dialog indicating Haskell source files.
        /// </summary>
        internal static string msgHaskellSourceFile {
            get {
                return ResourceManager.GetString("msgHaskellSourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyper Text Markup Language file|*.html;*.htm;*.shtml;*.shtm;*.xhtml;*.hta|A text in a file dialog indicating Hyper Text Markup Language files.
        /// </summary>
        internal static string msgHyperTextMarkupLanguageFile {
            get {
                return ResourceManager.GetString("msgHyperTextMarkupLanguageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inno Setup Script File|*.iss|A text in a file dialog indicating Inno Setup Script files.
        /// </summary>
        internal static string msgInnoSetupScriptFile {
            get {
                return ResourceManager.GetString("msgInnoSetupScriptFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java script file|*.js|A text in a file dialog indicating Java script files.
        /// </summary>
        internal static string msgJavaScriptFile {
            get {
                return ResourceManager.GetString("msgJavaScriptFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JavaServer pages file|*.jsp|A text in a file dialog indicating JavaServer pages files.
        /// </summary>
        internal static string msgJavaServerPagesFile {
            get {
                return ResourceManager.GetString("msgJavaServerPagesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java source file|*.java|A text in a file dialog indicating Java source files.
        /// </summary>
        internal static string msgJavaSourceFile {
            get {
                return ResourceManager.GetString("msgJavaSourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KiXtart file|*.kix|A text in a file dialog indicating KiXtart files.
        /// </summary>
        internal static string msgKiXtartFile {
            get {
                return ResourceManager.GetString("msgKiXtartFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Processing language file|*.lsp;*.lisp|A text in a file dialog indicating List Processing language files.
        /// </summary>
        internal static string msgListProcessingLanguageFile {
            get {
                return ResourceManager.GetString("msgListProcessingLanguageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua source file|*.lua|A text in a file dialog indicating Lua source files.
        /// </summary>
        internal static string msgLuaSourceFile {
            get {
                return ResourceManager.GetString("msgLuaSourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makefile|*.mak|A text in a file dialog indicating Makefile files.
        /// </summary>
        internal static string msgMakeFile {
            get {
                return ResourceManager.GetString("msgMakeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MATrix LABoratory file|*.m|A text in a file dialog indicating MATrix LABoratory files.
        /// </summary>
        internal static string msgMATrixLABoratoryFile {
            get {
                return ResourceManager.GetString("msgMATrixLABoratoryFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSDOS Style/ASCII Art file|*.nfo|A text in a file dialog indicating MSDOS Style/ASCII Art file files.
        /// </summary>
        internal static string msgMSDOSStyleAsciiArtFile {
            get {
                return ResourceManager.GetString("msgMSDOSStyleAsciiArtFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS INI file|*.ini;*.inf;*.reg;*.url|A text in a file dialog indicating MS INI files.
        /// </summary>
        internal static string msgMSIniFile {
            get {
                return ResourceManager.GetString("msgMSIniFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal text file|*.txt|A text in a file dialog indicating .txt files.
        /// </summary>
        internal static string msgNormalTextFile {
            get {
                return ResourceManager.GetString("msgNormalTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullsoft Scriptable Install System script file|*.nsi;*.nsh|A text in a file dialog indicating Nullsoft Scriptable Install System script files.
        /// </summary>
        internal static string msgNullsoftScriptableInstallSystemScriptFile {
            get {
                return ResourceManager.GetString("msgNullsoftScriptableInstallSystemScriptFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open|A title for a open file dialog.
        /// </summary>
        internal static string msgOpenFile {
            get {
                return ResourceManager.GetString("msgOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pascal source file|*.pas|A text in a file dialog indicating Pascal source files.
        /// </summary>
        internal static string msgPascalSourceFile {
            get {
                return ResourceManager.GetString("msgPascalSourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perl source file|*.pl;*.pm;*.plx|A text in a file dialog indicating Perl source files.
        /// </summary>
        internal static string msgPerlSourceFile {
            get {
                return ResourceManager.GetString("msgPerlSourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Hypertext Preprocessor file|*.php;*.php3;*.phtml|A text in a file dialog indicating PHP Hypertext Preprocessor files.
        /// </summary>
        internal static string msgPHPHypertextPreprocessorFile {
            get {
                return ResourceManager.GetString("msgPHPHypertextPreprocessorFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostScript file|*.ps|A text in a file dialog indicating PostScript files.
        /// </summary>
        internal static string msgPostScriptFile {
            get {
                return ResourceManager.GetString("msgPostScriptFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties file|*.properties|A text in a file dialog indicating Properties files.
        /// </summary>
        internal static string msgPropertiesFile {
            get {
                return ResourceManager.GetString("msgPropertiesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python file|*.py;*.pyw|A text in a file dialog indicating Python files.
        /// </summary>
        internal static string msgPythonFile {
            get {
                return ResourceManager.GetString("msgPythonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R programming language file|*.r|A text in a file dialog indicating R programming language files.
        /// </summary>
        internal static string msgRProgrammingLanguageFile {
            get {
                return ResourceManager.GetString("msgRProgrammingLanguageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruby file|*.rb;*.rbw|A text in a file dialog indicating Ruby files.
        /// </summary>
        internal static string msgRubyFile {
            get {
                return ResourceManager.GetString("msgRubyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As|A title for a save file as dialog.
        /// </summary>
        internal static string msgSaveFileAs {
            get {
                return ResourceManager.GetString("msgSaveFileAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheme file|*.scm;*.smd;*.ss|A text in a file dialog indicating Scheme files.
        /// </summary>
        internal static string msgSchemeFile {
            get {
                return ResourceManager.GetString("msgSchemeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script lines|As in the C# script type should be handling the Scintilla&apos;s contents as lines.
        /// </summary>
        internal static string msgScriptTypeLines {
            get {
                return ResourceManager.GetString("msgScriptTypeLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script text|As in the C# script type should be handling the Scintilla&apos;s contents as text.
        /// </summary>
        internal static string msgScriptTypeText {
            get {
                return ResourceManager.GetString("msgScriptTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smalltalk file|*.st|A text in a file dialog indicating Smalltalk files.
        /// </summary>
        internal static string msgSmalltalkFile {
            get {
                return ResourceManager.GetString("msgSmalltalkFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structured Query Language file|*.sql;*.sql_script|A text in a file dialog indicating Structured Query Language files.
        /// </summary>
        internal static string msgStructuredQueryLanguageFile {
            get {
                return ResourceManager.GetString("msgStructuredQueryLanguageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeX file|*.tex|A text in a file dialog indicating TeX files.
        /// </summary>
        internal static string msgTeXFile {
            get {
                return ResourceManager.GetString("msgTeXFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Command Language file|*.tlc|A text in a file dialog indicating Tool Command Language files.
        /// </summary>
        internal static string msgToolCommandLanguageFile {
            get {
                return ResourceManager.GetString("msgToolCommandLanguageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unix script file|*.sh;*.bsh|A text in a file dialog indicating Unix script files.
        /// </summary>
        internal static string msgUnixScriptFile {
            get {
                return ResourceManager.GetString("msgUnixScriptFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verilog file|*.vs;*.sv;*.vh;*.svh|A text in a file dialog indicating Verilog files.
        /// </summary>
        internal static string msgVerilogFile {
            get {
                return ResourceManager.GetString("msgVerilogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VHSIC Hardware Description Language file|*.vhd;*.vhdl|A text in a file dialog indicating VHSIC Hardware Description Language files.
        /// </summary>
        internal static string msgVHSICHardwareDescriptionLanguageFile {
            get {
                return ResourceManager.GetString("msgVHSICHardwareDescriptionLanguageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Basic file|*.vb;*.vbs|A text in a file dialog indicating Visual Basic files.
        /// </summary>
        internal static string msgVisualBasicFile {
            get {
                return ResourceManager.GetString("msgVisualBasicFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows PowerShell file|*.ps1;*.psm1|A text in a file dialog indicating Windows PowerShell files.
        /// </summary>
        internal static string msgWindowsPowerShellFile {
            get {
                return ResourceManager.GetString("msgWindowsPowerShellFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows resource file|*.rc|A text in a file dialog indicating Windows resource files.
        /// </summary>
        internal static string msgWindowsResourceFile {
            get {
                return ResourceManager.GetString("msgWindowsResourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YAML Ain&apos;t a Markup Language file|*.yml|A text in a file dialog indicating YAML Ain&apos;t a Markup Language files.
        /// </summary>
        internal static string msgYAMLFile {
            get {
                return ResourceManager.GetString("msgYAMLFile", resourceCulture);
            }
        }
    }
}
